### ISSUE TITLE
Error in certain cases involving recursive types

### ISSUE THREAD

**Issue by sirthias** [propensive/magnolia#73]
Here is test case that fails with the latest master but compiles fine with 0.6.1:

```scala
import magnolia.{CaseClass, Magnolia, SealedTrait}

trait Dibble[T]

object Dibble {

  def dummy[T]: Dibble[T] = new Dibble[T] {}

  type Typeclass[T] = Dibble[T]

  def combine[T](ctx: CaseClass[Dibble, T]): Dibble[T]    = dummy
  def dispatch[T](ctx: SealedTrait[Dibble, T]): Dibble[T] = dummy

  implicit def gen[T]: Dibble[T] = macro Magnolia.gen[T]

  implicit def forList[T: Dibble]: Dibble[List[T]] = dummy
}

object Test {
  case class Foo(list: List[Bar])
  case class Bar(inner: Bar)

  Dibble.gen[Foo]
}
```

This is the compiler error:

```
[error] .../Dibble.scala:33:13: not found: value barTypeclass$macro$3
[error]   Dibble.gen[Foo]
[error]             ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

I'll try to bisect to figure where the problem was introduced...

**Comment by sirthias** [comment]
For some reason this is a sporadic error that appears to be quite hard to reproduce consistently for me.
Even two sbt instances running concurrently against the exact magnolia dependency do not agree on whether the coded shown above, in it's own file, should compile fine or throw the compiler error.

Currently I know neither how to get into the "weird" compiler state showing this error, nor how to properly get out of it, which is quite frustrating.

I'll leave this open for now, though, in case anybody else sees this problem.

**Comment by joroKr21** [comment]
I don't think Magnolia is thread-safe :D

**Comment by propensive** [comment]
I think I have seen this too, if it's the same thing I mentioned on the Gitter channel recently... I wonder if it's anything to do with Magnolia's compile-time mutable state, and cache invalidation... (Surely not!?)

Glad, in a way, to hear it's not just me who had noticed this. @joroKr21 wasn't able to reproduce it.

My experience was that the first (IIRC) three runs of one particular test were consistently passing, but the fourth onwards was failing, consistently.

I will take a look, though haven't had so much time lately...

**Comment by joroKr21** [comment]
Shouldn't this example throw `DirectlyReentrantException` and fail?

**Comment by joroKr21** [comment]
It should give a reasonable error message though, and this should be tested.

**Comment by joroKr21** [comment]
Fixed by #186, the same problem as #185
