### ISSUE TITLE
Two parameters with default values cause type mismatch error

### ISSUE THREAD

**Issue by andreas-schroeder** [propensive/magnolia#227]
In version 0.14.1, typeclass derivation fails if a case class has two parameters with default values:

```scala
import org.scalatest.funsuite.AnyFunSuite

case class ParamsWithDefault(a: Int = 3, b: Int = 4)

class DefaultValuesTest extends AnyFunSuite {

  test("default values") {
    MyTypeClass.gen[ParamsWithDefault]
  }
}
```

Compilation error:

```
Error:(10, 20) type mismatch;
 found   : issues.ParamsWithDefault.type
 required: Int
    MyTypeClass.gen[ParamsWithDefault]
```

The code compiles with only one default value. Full typeclass code:

```scala

import magnolia._
import scala.language.experimental.macros

trait MyTypeClass[T] {
  def name: String
}

object MyTypeClass {

  implicit def gen[T]: Typeclass[T] = macro Magnolia.gen[T]

  type Typeclass[T] = MyTypeClass[T]

  implicit val forInt: Typeclass[Int] = new Typeclass[Int] {
    def name: String = "Int"
  }

  def dispatch[T](ctx: SealedTrait[Typeclass, T]): Typeclass[T] =
    new Typeclass[T] {
      def name: String = s"sealed trait ${ctx.typeName.full}"
    }

  def combine[T](ctx: CaseClass[Typeclass, T]): Typeclass[T] =
    new Typeclass[T] {
      def name: String = s"case class ${ctx.typeName.full}"
    }

}
```

**Comment by propensive** [comment]
There's something a little surprising about this. I've derived for case classes with more than one default parameter before, and it has worked fine. Do you know if the error afflicts earlier versions too?

**Comment by andreas-schroeder** [comment]
Works with 0.12.8, seems like 0.13.1 broke it - Thanks for the quick response :)

**Comment by joroKr21** [comment]
Oh no, we don't have enough test coverage 🙈 
Thanks for reporting and sorry for fast and loose development.

**Comment by propensive** [comment]
Maybe it's worse now I've become a bit more efficient at making releases... :confused:
